version: '3'

services:
  app:
    container_name: example_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:4000"
      - "80:${APP_PORT}"
    env_file:
      - .env